### ISSUE TITLE
Sometimes CPU variant detection is wrong

### ISSUE THREAD

**Issue by aviraxp** [rovo89/XposedTools#15]
I got a report from a user whose cellphone contains a Snapdragon 652, which is ARM64 for sure, and Xposed Installer can detect this CPU variant and download zip for ARM64. However, either he installs the zip via recovery or installer, it always throws an error message which says that his CPU variant is ARM and he is installing on the wrong platform. 

I checked build.prop, and found this line: `ro.product.cpu.abi=arm64-v8a`, which is right. From the research I did to the install script I can find nothing wrong. Can you suggest some possible reasons?

**Comment by rovo89** [comment]
We are talking about the official ZIP files, right? There isn't much that could get wrong if the build.prop looks like you said. Is the Android version in the file correct?

**Comment by aviraxp** [comment]
I found a possible reason: The build.prop file has a white space at the end of each line, thus causes the issue. I suggest use `=~` instead of `=` in this part of the script to workaround it.

**Comment by rovo89** [comment]
That's probably the reason. What kind of ROM is that? Could the ROM be fixed instead?

**Comment by aviraxp** [comment]
I have got some these kinds of reports before and they came from various ROMs and manufactures, so I think there is something wrong with their build script (probably they use a same open-source build.prop generator  that have this issue), but I don't think this can be fixed on the ROM side because they are all stock roms which have bad fame that never listen to user's issue reports.

**Comment by rovo89** [comment]
I see. Well, then I'd prefer to change this function in a way that it removes any trailing whitespace:
https://github.com/rovo89/XposedTools/blob/master/zipstatic/_all/META-INF/com/google/android/flash-script.sh#L10
Not sure if that can be integrated into the `REGEX` or if an additional `sed` would be easier.

**Comment by aviraxp** [comment]
Any updates on this? Some users are still suffering from it.

**Comment by drhouse** [comment]
I don't know if it's related, but I just installed Xposed_Installer.apk v3.1.5, when I ran it I saw the option to '_Install via recovery_', since I already had TWRP setup, I chose it. 

During installation, the CLI showed it had detected and remotely downloaded the '**arm64**' version, although when I had previously checked with CPU-Z.apk it said my architecture was '**armv7I**' which I've read means it should've picked '**arm**'. 

However, after the 10+ minutes boot, the Xposed Installer showed a green checkmark with '_Xposed Framework version 89 is active_'... so, somehow it still worked for some reason.
